[package]
name = "rpgmv-types"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1.0.204", features = [ "derive" ] }

[dev-dependencies]
serde_json = "1.0.120"
