[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
ignore = [
    # Used by an egui feature we don't use (accesskit).
    "RUSTSEC-2024-0436",
]

[licenses]
confidence-threshold = 0.93
private = { ignore = true }
allow = [ 
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "Unicode-3.0", 
    "CDLA-Permissive-2.0", 
    "MPL-2.0", 
    "ISC", 
    "Zlib", 
    "BSL-1.0", 
    "OFL-1.1", 
    "Ubuntu-font-1.0", 
    "BSD-2-Clause",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[[licenses.clarify]]
name = "encoding_rs"
version = "*"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0x39f8ad31 }
]

[bans]
multiple-versions = "warn"
highlight = "all"
skip = [
    { name = "windows_x86_64_msvc", version = "0.48.5" },
    { name = "windows_x86_64_gnu", version = "0.48.5" },
    { name = "windows-targets", version = "0.48.5" },
    { name = "windows-sys", version = "0.52.0" },
    { name = "webpki-roots", version = "0.26.11" },
    { name = "toml", version = "0.5.11" },
    { name = "thiserror-impl", version = "1.0.69" },
    { name = "thiserror", version = "1.0.69" },
    { name = "siphasher", version = "0.3.11" },
    { name = "rustix", version = "0.38.44" },
    { name = "quick-xml", version = "0.30.0" },
    { name = "objc2-foundation", version = "0.2.2" },
    { name = "objc2-app-kit", version = "0.2.2" },
    { name = "objc2", version = "0.5.2" },
    { name = "linux-raw-sys", version = "0.4.15" },
    { name = "getrandom", version = "0.2.16" },
    { name = "dispatch2", version = "0.2.0" },
    { name = "core-foundation", version = "0.9.4" },
    { name = "block2", version = "0.5.1" },
    { name = "bitflags", version = "1.3.2" },
    { name = "base64", version = "0.21.7" },
    { name = "windows_x86_64_msvc", version = "0.52.6" },
    { name = "windows_x86_64_gnu", version = "0.52.6" },
    { name = "windows-targets", version = "0.52.6" },
           
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = [ "https://github.com/rust-lang/crates.io-index" ]

[sources.allow-org]
github = [
    "nathaniel-daniel",
]
