[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
ignore = [
    # Blocked on sctk-adwaita moving off of ab_glyph.
    "RUSTSEC-2026-0192",
    
    # Blocked on various wayland and d-bus crates updating quick-xml.
    "RUSTSEC-2026-0195",
    "RUSTSEC-2026-0194",
]

[licenses]
confidence-threshold = 0.93
private = { ignore = true }
allow = [ 
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "OFL-1.1",
    "Ubuntu-font-1.0",
    "Unicode-3.0",
    "Zlib",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[[licenses.clarify]]
name = "encoding_rs"
version = "*"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0x39f8ad31 }
]

[bans]
multiple-versions = "warn"
highlight = "all"
skip = [
    # These update frequently and take a while for the ecosystem to update.
    { name = "windows-sys", version = "0" },
    # { name = "windows-link", version = "0" },
    
    
    { name = "toml", version = "0.5.11" },
    { name = "thiserror-impl", version = "1.0.69" },
    { name = "thiserror", version = "1.0.69" },
    { name = "rustix", version = "0.38.44" },
    { name = "objc2-foundation", version = "0.2.2" },
    { name = "objc2-app-kit", version = "0.2.2" },
    { name = "objc2", version = "0.5.2" },
    { name = "linux-raw-sys", version = "0.4.15" },
    { name = "getrandom", version = "0.2.16" },
    { name = "core-foundation", version = "0.9.4" },
    { name = "block2", version = "0.5.1" },
    { name = "bitflags", version = "1.3.2" },
    { name = "windows_x86_64_msvc", version = "0.52.6" },
    { name = "windows_x86_64_gnu", version = "0.52.6" },
    { name = "windows-targets", version = "0.52.6" },
    { name = "smithay-client-toolkit", version = "0.19.2" },
    { name = "png", version = "0.17.16" },
    { name = "hashbrown", version = "0.15.5" },
    { name = "calloop-wayland-source", version = "0.3.0" },
    { name = "calloop", version = "0.13.0" },
    { name = "getrandom", version = "0.3.4" },
    { name = "heck", version = "0.4.1" },
    { name = "rustc-hash", version = "1.1.0" },
    { name = "phf_shared", version = "0.11.3" },
    { name = "phf", version = "0.11.3" },
    { name = "kurbo", version = "0.11.3" },
    { name = "foldhash", version = "0.1.5" },
    { name = "hashbrown", version = "0.16.1" },
    { name = "accesskit_consumer", version = "0.35.0" },
    { name = "accesskit_consumer", version = "0.36.0" },
    { name = "syn", version = "2.0.119" },
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = [ "https://github.com/rust-lang/crates.io-index" ]

[sources.allow-org]
github = [
    "nathaniel-daniel",
]
