[package]
name = "rpgmv-image-viewer"
version = "0.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.98"
eframe = "0.31.1"
egui-toast = "0.17.0"
egui_extras = { version = "0.31.1", features = ["all_loaders"] }
env_logger = "0.11.8"
image = { version = "0.25.6", features = [ "png", "ico" ], default-features = false }
rayon = "1.10.0"
rfd = { version = "0.15.3", features = [ "xdg-portal", "tokio" ], default-features = false }
rpgmvp = { version = "0.0.0", path = "../rpgmvp" }
tokio = "1.45.0"

[build-dependencies]
winres = "0.1.12"
