name: Nightly
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-nightly-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: make build-release-windows

      - name: List
        run: ls target/x86_64-pc-windows-msvc/release/rpgmv-image-viewer.exe

      - name: Release nightly
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          name: nightly
          tag_name: nightly
          files: target/x86_64-pc-windows-msvc/release/rpgmv-image-viewer.exe
          fail_on_unmatched_files: true
